image: python:3.13

stages:
  - deploy

pages:
#  tags:
#    - sphinx
  stage: deploy
  script:
    - python3 -m pip install -r requirements.txt -r requirements-sphinx.txt
    - (export FILE_LOGGER="False" ; sphinx-build -M html docs/source/ public/)
  artifacts:
    paths:
      - public
#    only:
#      - master
#      - dev