name: cassis-lte-python3.10
channels:
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - astropy
  - lmfit
  - pandas
  - spectral-cube
  - regions
  - jupyter
